# Generated by Django 5.2.5 on 2025-08-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("short_description", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "background_image",
                    models.ImageField(upload_to="category_backgrounds/"),
                ),
                ("image", models.ImageField(upload_to="category_images/")),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
