# Generated by Django 5.2.5 on 2025-08-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
