# Generated by Django 5.2.5 on 2025-08-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_alter_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description_de",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="description_tr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="short_description_de",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="short_description_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="short_description_tr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="title_de",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="title_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="title_tr",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
