# Generated by Django 5.2.5 on 2025-08-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_category_description_de_category_description_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(editable=False, max_length=100, unique=True),
        ),
    ]
