# Generated by Django 5.2.5 on 2025-08-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_alter_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="order_number",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
